### ISSUE TITLE
Create the Splash Screen for the app

### ISSUE THREAD

**Issue by destrex271** [MicrosoftStudentChapter/notebook#1]

**Comment by tanmoysrt** [comment]
can you assign this to me ? I am experienced in flutter.

**Comment by destrex271** [comment]
> can you assign this to me ? I am experienced in flutter.


The PR's would be merged on a First Come First Serve basis, so you can start right away no need to wait for any assignment approvals from the maintainers.

**Comment by pratikagr** [comment]
assign

**Comment by tanmoysrt** [comment]
@destrex271 i have submitted the PR request check once please #9
