### ISSUE TITLE
Expanded Notes view

### ISSUE THREAD

**Issue by destrex271** [MicrosoftStudentChapter/notebook#6]
Screen for detailed view of a particular note from the list view screen.

**Comment by SwaroopSambhayya** [comment]
Hi, I would like to take up this issue

**Comment by destrex271** [comment]
> Hi, I would like to take up this issue

The PR's would be merged on a First Come First Serve basis, so you can start right away no need to wait for any assignment approvals from the maintainers.

**Comment by SwaroopSambhayya** [comment]
but for the contribution purpose is it possible to assign it to me?

**Comment by destrex271** [comment]
We are trying to give a chance to contribute to as many people as possible, so that is why we are not going to assign any issue to a specific person. You can pick up any issue and start working on it.

**Comment by SwaroopSambhayya** [comment]
Hi, I have created a PR #10 please review and merge

**Comment by destrex271** [comment]
> Hi, I have created a PR #10 please review and merge

Sure
